services:
  runner-manager:
    image: ${RUNNER_MANAGER_IMAGE}
    security_opt:
      - no-new-privileges:true
    networks:
      - runner_manager
      - mongodb
      - nats
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.20'
          memory: 150M
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
    environment:
      MONGO_SCHEME: ${BACKEND_MONGO_SCHEME}
      MONGO_USERNAME: ${BACKEND_MONGO_USERNAME}
      MONGO_PASSWORD: ${BACKEND_MONGO_PASSWORD}
      MONGO_HOST: ${BACKEND_MONGO_HOST}
      MONGO_PORT: ${BACKEND_MONGO_PORT}
      MONGO_DATABASE_NAME: ${BACKEND_MONGO_DATABASE_NAME}
      NATS_URL: ${BACKEND_NATS_URL}
      OTEL_EXPORTER_OTLP_INSECURE: ${OTEL_EXPORTER_OTLP_INSECURE}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      PROFILING_ENABLED: ${PROFILING_ENABLED:-true}

networks:
  runner_manager:
    name: runner_manager
    external: true
  mongodb:
    name: mongodb
    external: true
  nats:
    name: nats
    external: true
  docker:
    name: docker
    external: true
