services:
  runner-worker-02:
    image: ${RUNNER_WORKER_IMAGE}
    networks:
      - nats
      - docker
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
    environment:
      RUNNER_WORKER_NAME: runner-worker-02
      NATS_URL: ${BACKEND_NATS_URL}
      DOCKER_HOST: ${BACKEND_DOCKER_HOST}

networks:
  nats:
    name: nats
    external: true
  docker:
    name: docker
    external: true
