services:
  runner-worker-03:
    image: ${RUNNER_WORKER_IMAGE}
    networks:
      - nats
      - docker
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
    environment:
      RUNNER_WORKER_NAME: runner-worker-03
      PRIVATE_KEY: ${BACKEND_PRIVATE_KEY}
      S3_ENDPOINT: ${BACKEND_S3_ENDPOINT}
      S3_ACCESS_KEY: ${BACKEND_S3_ACCESS_KEY}
      S3_SECRET_KEY: ${BACKEND_S3_SECRET_KEY}
      S3_BUCKET_NAME: ${BACKEND_S3_BUCKET_NAME}
      S3_USE_SSL: ${BACKEND_S3_USE_SSL}
      NATS_URL: ${BACKEND_NATS_URL}
      DOCKER_HOST: ${DOCKER_HOST}

networks:
  nats:
    name: nats
    external: true
  docker:
    name: docker
    external: true
