services:
  runner-worker-03:
    image: ${RUNNER_WORKER_IMAGE}
    security_opt:
      - no-new-privileges:true
    networks:
      - nats
      - docker
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
    environment:
      RUNNER_WORKER_NAME: runner-worker-03
      NATS_URL: ${BACKEND_NATS_URL}
      DOCKER_HOST: ${BACKEND_DOCKER_HOST}
      OTEL_EXPORTER_OTLP_INSECURE: ${OTEL_EXPORTER_OTLP_INSECURE}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
      OTEL_RESOURCE_ATTRIBUTES: ${OTEL_RESOURCE_ATTRIBUTES}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
      PROFILING_ENABLED: ${PROFILING_ENABLED:-true}

networks:
  nats:
    name: nats
    external: true
  docker:
    name: docker
    external: true
