services:
  app:
    image: ${APP_IMAGE}
    networks:
      - app
      - mongodb
      - nats
      - docker
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.20'
          memory: 150M
    environment:
      PRIVATE_KEY: ${BACKEND_PRIVATE_KEY}
      S3_ENDPOINT: ${BACKEND_S3_ENDPOINT}
      S3_ACCESS_KEY: ${BACKEND_S3_ACCESS_KEY}
      S3_SECRET_KEY: ${BACKEND_S3_SECRET_KEY}
      S3_BUCKET_NAME: ${BACKEND_S3_BUCKET_NAME}
      S3_USE_SSL: ${BACKEND_S3_USE_SSL}
      MONGO_SCHEME: ${BACKEND_MONGO_SCHEME}
      MONGO_USERNAME: ${BACKEND_MONGO_USERNAME}
      MONGO_PASSWORD: ${BACKEND_MONGO_PASSWORD}
      MONGO_HOST: ${BACKEND_MONGO_HOST}
      MONGO_PORT: ${BACKEND_MONGO_PORT}
      MONGO_DATABASE_NAME: ${BACKEND_MONGO_DATABASE_NAME}
      MAIL_SMTP_FROM: ${BACKEND_MAIL_SMTP_FROM}
      MAIL_SMTP_USERNAME: ${BACKEND_MAIL_SMTP_USERNAME}
      MAIL_SMTP_PASSWORD: ${BACKEND_MAIL_SMTP_PASSWORD}
      MAIL_SMTP_HOST: ${BACKEND_MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${BACKEND_MAIL_SMTP_PORT}
      NATS_URL: ${BACKEND_NATS_URL}
      DOCKER_HOST: ${DOCKER_HOST}

networks:
  app:
    name: app
    external: true
  mongodb:
    name: mongodb
    external: true
  nats:
    name: nats
    external: true
  docker:
    name: docker
    external: true
