services:
  runner-manager:
    image: ${RUNNER_MANAGER_IMAGE}
    networks:
      - runner_manager
      - mongodb
      - nats
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.20'
          memory: 150M
    environment:
      MONGO_SCHEME: ${BACKEND_MONGO_SCHEME}
      MONGO_USERNAME: ${BACKEND_MONGO_USERNAME}
      MONGO_PASSWORD: ${BACKEND_MONGO_PASSWORD}
      MONGO_HOST: ${BACKEND_MONGO_HOST}
      MONGO_PORT: ${BACKEND_MONGO_PORT}
      MONGO_DATABASE_NAME: ${BACKEND_MONGO_DATABASE_NAME}
      NATS_URL: ${BACKEND_NATS_URL}

networks:
  runner_manager:
    name: runner_manager
    external: true
  mongodb:
    name: mongodb
    external: true
  nats:
    name: nats
    external: true
  docker:
    name: docker
    external: true
