package article

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	mock2 "github.com/stretchr/testify/mock"

	"github.com/khanzadimahdi/testproject/application/auth"
	createarticle "github.com/khanzadimahdi/testproject/application/dashboard/article/createArticle"
	"github.com/khanzadimahdi/testproject/domain"
	"github.com/khanzadimahdi/testproject/domain/user"
	"github.com/khanzadimahdi/testproject/infrastructure/repository/mocks/articles"
	"github.com/khanzadimahdi/testproject/infrastructure/repository/mocks/languages"
	"github.com/khanzadimahdi/testproject/infrastructure/translator"
	"github.com/khanzadimahdi/testproject/infrastructure/validator"
)

func TestCreateHandler(t *testing.T) {
	t.Parallel()

	t.Run("create an article", func(t *testing.T) {
		t.Parallel()

		var (
			articleRepository  articles.MockArticlesRepository
			languageRepository languages.MockLanguagesRepository
			requestValidator   validator.MockValidator
			translator         translator.TranslatorMock

			r = createarticle.Request{
				Title:        "test title",
				Excerpt:      "test excerpt",
				Body:         "test body",
				AuthorUUID:   "test-author-uuid",
				Tags:         []string{"tag1", "tag2"},
				LanguageCode: "EN",
			}

			u = user.User{
				UUID: r.AuthorUUID,
			}

			au = "article-uuid"
		)

		requestValidator.On("Validate", &r).Once().Return(nil)
		defer requestValidator.AssertExpectations(t)

		languageRepository.On("Exists", "EN").Once().Return(true)
		defer languageRepository.AssertExpectations(t)

		articleRepository.On("Save", mock2.AnythingOfType("*article.Article")).Once().Return(au, nil)
		defer articleRepository.AssertExpectations(t)

		handler := NewCreateHandler(createarticle.NewUseCase(&articleRepository, &languageRepository, &requestValidator, &translator))

		var payload bytes.Buffer
		err := json.NewEncoder(&payload).Encode(r)
		assert.NoError(t, err)

		request := httptest.NewRequest(http.MethodGet, "/", &payload)
		request = request.WithContext(auth.ToContext(request.Context(), &u))
		response := httptest.NewRecorder()

		handler.ServeHTTP(response, request)

		// the correlation uuid is generated by the use case, so assert the shape
		// rather than an exact value.
		var body map[string]string
		err = json.Unmarshal(response.Body.Bytes(), &body)
		assert.NoError(t, err)

		assert.Equal(t, "application/json", response.Header().Get("content-type"))
		assert.Equal(t, "EN", body["language_code"])
		assert.NotEmpty(t, body["correlation_uuid"])
		assert.Equal(t, http.StatusCreated, response.Code)
	})

	t.Run("validation failed", func(t *testing.T) {
		t.Parallel()

		var (
			articleRepository  articles.MockArticlesRepository
			languageRepository languages.MockLanguagesRepository
			requestValidator   validator.MockValidator
			translator         translator.TranslatorMock

			u = user.User{
				UUID: "test-author-uuid",
			}
		)

		requestValidator.On("Validate", &createarticle.Request{AuthorUUID: u.UUID}).Once().Return(domain.ValidationErrors{
			"body":          "body is required",
			"excerpt":       "excerpt is required",
			"title":         "title is required",
			"language_code": "language is required",
		})
		defer requestValidator.AssertExpectations(t)

		handler := NewCreateHandler(createarticle.NewUseCase(&articleRepository, &languageRepository, &requestValidator, &translator))

		request := httptest.NewRequest(http.MethodGet, "/", bytes.NewBufferString("{}"))
		request = request.WithContext(auth.ToContext(request.Context(), &u))
		response := httptest.NewRecorder()

		handler.ServeHTTP(response, request)

		articleRepository.AssertNotCalled(t, "Save")

		expected, err := os.ReadFile("testdata/create-article-validation-errors-response.json")
		assert.NoError(t, err)

		assert.Equal(t, "application/json", response.Header().Get("content-type"))
		assert.JSONEq(t, string(expected), response.Body.String())
		assert.Equal(t, http.StatusBadRequest, response.Code)
	})
}
