export const INTERNAL_BACKEND_URL = process.env.INTERNAL_BACKEND_BASE_URL;
export const EXTERNAL_BACKEND_URL =
  process.env.NEXT_PUBLIC_EXTERNAL_BACKEND_BASE_URL;
export const FILES_PUBLIC_URL = `${process.env.NEXT_PUBLIC_FILES_BASE_URL}/files`;
