services:
  proxy:
    image: ${PROXY_IMAGE}
    networks:
      - proxy
      - frontend
      - app
      - mongodb_dashboard
      - docker_dashboard
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - 80:80

networks:
  proxy:
    name: proxy
  frontend:
    name: frontend
    external: true
  app:
    name: app
    external: true
  mongodb_dashboard:
    name: mongodb_dashboard
    external: true
  docker_dashboard:
    name: docker_dashboard
    external: true
