services:
  nats:
    image: nats:2.10
    networks:
      - nats
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - ${VOLUME_PATH}/nats:/data
    command: ["--jetstream", "--http_port", "8222", "--port", "4222", "--store_dir", "/data"]

networks:
  nats:
    name: nats
