services:
  docker:
    image: docker:27-dind
    networks:
      - docker
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    runtime: sysbox-runc
    # privileged: true # To test localy: enable this line and disable runtime
    environment:
      DOCKER_TLS_CERTDIR: "" # disable certs

networks:
  docker:
    name: docker
