services:
  nats:
    image: nats:2.10
    restart: unless-stopped
    networks:
      - nats
    volumes:
      - ${VOLUME_PATH}/nats:/data
    command: ["--jetstream", "-m", "8222", "-p", "4222"]

networks:
  nats:
    name: nats
